### ISSUE TITLE
Nothing but 500 errors when trying to use REST api from plugin

### ISSUE THREAD

**Issue by nneul** [codeclou/customfield-editor-plugin#20]
```
{
  "statusCode": 500,
  "subCode": 5002003,
  "message": "Unexpected Error: java.lang.NullPointerException"
}
```

and 

```
2017-02-28 16:22:30,198 http-nio-8080-exec-18 WARN nneul 982x63159x1 n80aov 131.151.49.1,0:0:0:0:0:0:0:1 /rest/jiracustomfieldeditorplugin/1.2/user/customfields/10800/contexts/default/options [i.c.c.editor.rest.Bas
eResource] Unexpected Error. subCode: 5002003
java.lang.NullPointerException
        at io.codeclou.customfield.editor.components.notexported.impl.CustomFieldHelperImpl.createOrUpdateOption(CustomFieldHelperImpl.java:885)
        at io.codeclou.customfield.editor.rest.official.UserCustomFieldResource.createOption(UserCustomFieldResource.java:319)
        at io.codeclou.customfield.editor.rest.official.UserCustomFieldResource.createOptionInDefaultContext(UserCustomFieldResource.java:359)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        ... 1 filtered
        at java.lang.reflect.Method.invoke(Method.java:498)
        ... 19 filtered
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:154)
        ... 1 filtered
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:68)
        ... 36 filtered
        at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
        ... 53 filtered
        at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:80)
        ... 1 filtered
        at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:78)
        ... 16 filtered
        at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:37)
        ... 20 filtered
        at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
        ... 10 filtered
        at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
        ... 4 filtered
        at com.atlassian.web.servlet.plugin.LocationCleanerFilter.doFilter(LocationCleanerFilter.java:36)
        ... 29 filtered
        at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
        ... 28 filtered
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

Any ideas/suggestions for diagnosing?

This is on a current 7.3.1 install.

**Comment by nneul** [comment]
Note that the web UI works fine.

**Comment by clouless** [comment]
The Web-GUI uses the same Rest-API. So I guess something with your request is not quite right.
 * Do you send Basic-Auth Headers with your request.
 * Can you try the Rest-Api-Explorer and send the request from there
 * With which software do you work with the rest API? Can paste some code snippet how the request looks like
 * Which version of the Plugin do you use and which version of JIRA do you use?

**Comment by nneul** [comment]
I was just using the REST Explorer in your gui. If I copy the curl example, it results in the same error.

I was trying to just add an option. 

1.2.3 for the plugin, 7.3.1 for jira. 

Your comment about about "uses the same rest api" was very helpful. Turns out - the problem is if you actually use the example schema that is presented in the rest explorer - with passing a 0 for id and sequence - it generates a 500 error. If I leave those off, it works fine. Thank you.

**Comment by nneul** [comment]
If any value is passed for id - it fails. I see now in the example docs that use of sequence is discouraged. 

Either way - I would expect the example/model schema to actually be a valid/working request.

**Comment by clouless** [comment]
Good to hear that it works now. Since the Doc is autogenerated from Java-Classes it cannot be so fine grained but I will try to do my best to update the doc accordingly :)
